<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;
class RegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $regions = array(
            array('province_id' => '1','name' => 'Нукус шаҳри'),
            array('province_id' => '1','name' => 'Амударё тумани'),
            array('province_id' => '1','name' => 'Беруний тумани'),
            array('province_id' => '1','name' => 'Кегейли тумани'),
            array('province_id' => '1','name' => 'Қонликўл тумани'),
            array('province_id' => '1','name' => 'Қораўзак тумани'),
            array('province_id' => '1','name' => 'Қўнғирот тумани'),
            array('province_id' => '1','name' => 'Мўйноқ тумани'),
            array('province_id' => '1','name' => 'Нукус тумани'),
            array('province_id' => '1','name' => 'Тахиатош тумани'),
            array('province_id' => '1','name' => 'Тахтакўпир тумани'),
            array('province_id' => '1','name' => 'Тўрткўл тумани'),
            array('province_id' => '1','name' => 'Хўжайли тумани'),
            array('province_id' => '1','name' => 'Чимбой тумани'),
            array('province_id' => '1','name' => 'Шуманай тумани'),
            array('province_id' => '1','name' => 'Элликқалъа тумани'),
            array('province_id' => '2','name' => 'Андижон шаҳри'),
            array('province_id' => '2','name' => 'Андижон тумани'),
            array('province_id' => '2','name' => 'Асака тумани'),
            array('province_id' => '2','name' => 'Балиқчи тумани'),
            array('province_id' => '2','name' => 'Бўз тумани,'),
            array('province_id' => '2','name' => 'Булоқбоши тумани'),
            array('province_id' => '2','name' => 'Жалақудуқ тумани'),
            array('province_id' => '2','name' => 'Избоскан тумани'),
            array('province_id' => '2','name' => 'Қўрғонтепа тумани'),
            array('province_id' => '2','name' => 'Марҳамат тумани'),
            array('province_id' => '2','name' => 'Олтинкўл тумани'),
            array('province_id' => '2','name' => 'Пахтаобод тумани'),
            array('province_id' => '2','name' => 'Улуғнор тумани'),
            array('province_id' => '2','name' => 'Хонобод шаҳри'),
            array('province_id' => '2','name' => 'Хўжаобод тумани'),
            array('province_id' => '2','name' => 'Шаҳрихон тумани'),
            array('province_id' => '3','name' => 'Бухоро шаҳри'),
            array('province_id' => '3','name' => 'Когон шаҳри'),
            array('province_id' => '3','name' => 'Бухоро тумани'),
            array('province_id' => '3','name' => 'Вобкент тумани'),
            array('province_id' => '3','name' => 'Ғиждувон тумани'),
            array('province_id' => '3','name' => 'Жондор тумани'),
            array('province_id' => '3','name' => 'Когон тумани'),
            array('province_id' => '3','name' => 'Қоракўл тумани'),
            array('province_id' => '3','name' => 'Қоровулбозор тумани'),
            array('province_id' => '3','name' => 'Олот тумани'),
            array('province_id' => '3','name' => 'Пешку тумани'),
            array('province_id' => '3','name' => 'Ромитан тумани'),
            array('province_id' => '3','name' => 'Шофиркон тумани'),
            array('province_id' => '4','name' => 'Жиззах шаҳри'),
            array('province_id' => '4','name' => 'Арнасой тумани'),
            array('province_id' => '4','name' => 'Бахмал тумани'),
            array('province_id' => '4','name' => 'Ғаллаорол тумани'),
            array('province_id' => '4','name' => 'Дўстлик тумани'),
            array('province_id' => '4','name' => 'Зарбдор тумани'),
            array('province_id' => '4','name' => 'Зафаробод тумани'),
            array('province_id' => '4','name' => 'Зомин тумани'),
            array('province_id' => '4','name' => 'Мирзачўл тумани'),
            array('province_id' => '4','name' => 'Пахтакор тумани'),
            array('province_id' => '4','name' => 'Фориш тумани'),
            array('province_id' => '4','name' => 'Ш.Рашидов тумани'),
            array('province_id' => '4','name' => 'Янгиобод тумани'),
            array('province_id' => '5','name' => 'Қарши шаҳри'),
            array('province_id' => '5','name' => 'Шаҳрисабз шаҳри'),
            array('province_id' => '5','name' => 'Ғузор тумани'),
            array('province_id' => '5','name' => 'Деҳқонобод тумани'),
            array('province_id' => '5','name' => 'Касби тумани'),
            array('province_id' => '5','name' => 'Китоб тумани'),
            array('province_id' => '5','name' => 'Косон тумани'),
            array('province_id' => '5','name' => 'Қамаши тумани'),
            array('province_id' => '5','name' => 'Қарши тумани'),
            array('province_id' => '5','name' => 'Миришкор тумани'),
            array('province_id' => '5','name' => 'Муборак тумани'),
            array('province_id' => '5','name' => 'Нишон тумани'),
            array('province_id' => '5','name' => 'Чироқчи тумани'),
            array('province_id' => '5','name' => 'Шаҳрисабз тумани'),
            array('province_id' => '5','name' => 'Яккабоғ тумани'),
            array('province_id' => '6','name' => 'Навоий шаҳри'),
            array('province_id' => '6','name' => 'Зарафшон шаҳри'),
            array('province_id' => '6','name' => 'Кармана тумани'),
            array('province_id' => '6','name' => 'Конимех тумани'),
            array('province_id' => '6','name' => 'Қизилтепа тумани'),
            array('province_id' => '6','name' => 'Навбаҳор тумани'),
            array('province_id' => '6','name' => 'Нурота тумани'),
            array('province_id' => '6','name' => 'Томди тумани'),
            array('province_id' => '6','name' => 'Учқудуқ тумани'),
            array('province_id' => '6','name' => 'Хатирчи тумани'),
            array('province_id' => '7','name' => 'Наманган шаҳри'),
            array('province_id' => '7','name' => 'Косонсой тумани'),
            array('province_id' => '7','name' => 'Мингбулоқ тумани'),
            array('province_id' => '7','name' => 'Наманган тумани'),
            array('province_id' => '7','name' => 'Норин тумани'),
            array('province_id' => '7','name' => 'Поп тумани'),
            array('province_id' => '7','name' => 'Тўрақўрғон тумани'),
            array('province_id' => '7','name' => 'Уйчи тумани'),
            array('province_id' => '7','name' => 'Учқўрғон тумани'),
            array('province_id' => '7','name' => 'Чортоқ тумани'),
            array('province_id' => '7','name' => 'Чуст тумани'),
            array('province_id' => '7','name' => 'Янгиқўрғон тумани'),
            array('province_id' => '8','name' => 'Самарқанд шаҳри'),
            array('province_id' => '8','name' => 'Каттақўрғон шаҳри'),
            array('province_id' => '8','name' => 'Булунғур тумани'),
            array('province_id' => '8','name' => 'Жомбой тумани'),
            array('province_id' => '8','name' => 'Иштихон тумани'),
            array('province_id' => '8','name' => 'Каттақўрғон тумани'),
            array('province_id' => '8','name' => 'Қўшробод тумани'),
            array('province_id' => '8','name' => 'Нарпай тумани'),
            array('province_id' => '8','name' => 'Нуробод тумани'),
            array('province_id' => '8','name' => 'Оқдарё тумани'),
            array('province_id' => '8','name' => 'Пайариқ тумани'),
            array('province_id' => '8','name' => 'Пастдарғом тумани'),
            array('province_id' => '8','name' => 'Пахтачи тумани'),
            array('province_id' => '8','name' => 'Самарқанд тумани'),
            array('province_id' => '8','name' => 'Тайлоқ тумани'),
            array('province_id' => '8','name' => 'Ургут тумани'),
            array('province_id' => '9','name' => 'Гулистон шаҳри'),
            array('province_id' => '9','name' => 'Ширин шаҳри'),
            array('province_id' => '9','name' => 'Янгиер шаҳри'),
            array('province_id' => '9','name' => 'Боёвут тумани'),
            array('province_id' => '9','name' => 'Гулистон тумани'),
            array('province_id' => '9','name' => 'Мирзаобод тумани'),
            array('province_id' => '9','name' => 'Оқолтин тумани'),
            array('province_id' => '9','name' => 'Сайхунобод тумани'),
            array('province_id' => '9','name' => 'Сардоба тумани'),
            array('province_id' => '9','name' => 'Сирдарё тумани'),
            array('province_id' => '9','name' => 'Ховос тумани'),
            array('province_id' => '10','name' => 'Термиз шаҳри'),
            array('province_id' => '10','name' => 'Ангор тумани'),
            array('province_id' => '10','name' => 'Бойсун тумани'),
            array('province_id' => '10','name' => 'Денов тумани'),
            array('province_id' => '10','name' => 'Жарқўрғон тумани'),
            array('province_id' => '10','name' => 'Қизириқ тумани'),
            array('province_id' => '10','name' => 'Қумқўрғон тумани'),
            array('province_id' => '10','name' => 'Музробод тумани'),
            array('province_id' => '10','name' => 'Олтинсой тумани'),
            array('province_id' => '10','name' => 'Сариосиё тумани'),
            array('province_id' => '10','name' => 'Термиз тумани'),
            array('province_id' => '10','name' => 'Узун тумани'),
            array('province_id' => '10','name' => 'Шеробод тумани'),
            array('province_id' => '10','name' => 'Шўрчи тумани'),
            array('province_id' => '11','name' => 'Ангрен шаҳри'),
            array('province_id' => '11','name' => 'Бекобод шаҳри'),
            array('province_id' => '11','name' => 'Нурафшон шаҳри'),
            array('province_id' => '11','name' => 'Олмалиқ шаҳри'),
            array('province_id' => '11','name' => 'Оҳангарон шаҳри'),
            array('province_id' => '11','name' => 'Чирчиқ шаҳри'),
            array('province_id' => '11','name' => 'Янгийўл шаҳри'),
            array('province_id' => '11','name' => 'Бекобод тумани'),
            array('province_id' => '11','name' => 'Бўка тумани'),
            array('province_id' => '11','name' => 'Бўстонлиқ тумани'),
            array('province_id' => '11','name' => 'Зангиота тумани'),
            array('province_id' => '11','name' => 'Қибрай тумани'),
            array('province_id' => '11','name' => 'Қуйичирчиқ тумани'),
            array('province_id' => '11','name' => 'Оққўрғон тумани'),
            array('province_id' => '11','name' => 'Оҳангарон тумани'),
            array('province_id' => '11','name' => 'Паркент тумани'),
            array('province_id' => '11','name' => 'Пскент тумани'),
            array('province_id' => '11','name' => 'Тошкент тумани'),
            array('province_id' => '11','name' => 'Ўртачирчиқ тумани'),
            array('province_id' => '11','name' => 'Чиноз тумани'),
            array('province_id' => '11','name' => 'Юқоричирчиқ тумани'),
            array('province_id' => '11','name' => 'Янгийўл тумани'),
            array('province_id' => '12','name' => 'Фарғона шаҳри'),
            array('province_id' => '12','name' => 'Қувасой шаҳри'),
            array('province_id' => '12','name' => 'Қўқон шаҳри'),
            array('province_id' => '12','name' => 'Марғилон шаҳри'),
            array('province_id' => '12','name' => 'Бешариқ тумани'),
            array('province_id' => '12','name' => 'Боғдод тумани'),
            array('province_id' => '12','name' => 'Бувайда тумани'),
            array('province_id' => '12','name' => 'Данғара тумани'),
            array('province_id' => '12','name' => 'Ёзёвон тумани'),
            array('province_id' => '12','name' => 'Қува тумани'),
            array('province_id' => '12','name' => 'Қўштепа тумани'),
            array('province_id' => '12','name' => 'Олтиариқ тумани'),
            array('province_id' => '12','name' => 'Риштон тумани'),
            array('province_id' => '12','name' => 'Сўх тумани'),
            array('province_id' => '12','name' => 'Тошлоқ тумани'),
            array('province_id' => '12','name' => 'Ўзбекистон тумани'),
            array('province_id' => '12','name' => 'Учкўприк тумани'),
            array('province_id' => '12','name' => 'Фарғона тумани'),
            array('province_id' => '12','name' => 'Фурқат тумани'),
            array('province_id' => '13','name' => 'Урганч шаҳри'),
            array('province_id' => '13','name' => 'Хива шаҳри'),
            array('province_id' => '13','name' => 'Боғот тумани'),
            array('province_id' => '13','name' => 'Гурлан тумани'),
            array('province_id' => '13','name' => 'Қўшкўпир тумани'),
            array('province_id' => '13','name' => 'Урганч тумани'),
            array('province_id' => '13','name' => 'Хива тумани'),
            array('province_id' => '13','name' => 'Хозарасп тумани'),
            array('province_id' => '13','name' => 'Ҳонқа тумани'),
            array('province_id' => '13','name' => 'Шовот тумани'),
            array('province_id' => '13','name' => 'Янгиариқ тумани'),
            array('province_id' => '13','name' => 'Янгибозор тумани'),
            array('province_id' => '14','name' => 'Бектемир тумани'),
            array('province_id' => '14','name' => 'М.Улуғбек тумани'),
            array('province_id' => '14','name' => 'Миробод тумани'),
            array('province_id' => '14','name' => 'Олмазор тумани'),
            array('province_id' => '14','name' => 'Сергели тумани'),
            array('province_id' => '14','name' => 'Учтепа тумани'),
            array('province_id' => '14','name' => 'Чилонзор тумани'),
            array('province_id' => '14','name' => 'Шайхонтоҳур тумани'),
            array('province_id' => '14','name' => 'Юнусобод тумани'),
            array('province_id' => '14','name' => 'Яккасарой тумани'),
            array('province_id' => '14','name' => 'Яшнобод тумани'),
            array('province_id' => '14','name' => 'Янги Хаёт'),
            array('province_id' => '10','name' => 'Бандихон тумани'),
            array('province_id' => '13','name' => 'Тупроккала тумани'),
            array('province_id' => '7','name' => 'Янги Наманган'),
            array('province_id' => '7','name' => 'Давлатобод')
          );
           \App\Models\Region::insert($regions);

    }
}
